export default [
    {
        date: '2023-03-21',
        name: '*洋',
        money: 9.9,
        method: '微信',
        message: 'POT加油！赶超bob！'
    }, {
        date: '2023-05-02',
        name: '*珂',
        money: 9.99,
        method: '支付宝',
        message: '宝宝加油！'
    }, {
        date: '2023-05-07',
        name: 'E*i',
        money: 9.9,
        method: '微信',
        message: ''
    }, {
        date: '2023-05-13',
        name: 'kingxiaofire',
        money: 8.88,
        method: '微信',
        message: '请大佬喝瓶水'
    }, {
        date: '2023-05-13',
        name: '**江',
        money: 6.66,
        method: '支付宝',
        message: ''
    }, {
        date: '2023-05-17',
        name: 'hoochanlon',
        money: 10.0,
        method: '微信',
        message: ''
    }, {
        date: '2023-05-18',
        name: 'L*i',
        money: 11.11,
        method: '微信',
        message: ''
    }, {
        date: '2023-05-19',
        name: 'Integral🏳️‍🌈',
        money: 18.88,
        method: '支付宝',
        message: '希望早日完善 Wayland 支持'
    }, {
        date: '2023-05-19',
        name: '帅哥yfn86',
        money: 6.66,
        method: '支付宝',
        message: ''
    }, {
        date: '2023-05-23',
        name: '*雪',
        money: 2.00,
        method: '微信',
        message: ''
    }, {
        date: '2023-05-25',
        name: 'AI.LS',
        money: 18.88,
        method: '微信',
        message: ''
    }, {
        date: '2023-05-26',
        name: '14CC',
        money: 2.88,
        method: '微信',
        message: '很好的工具'
    }, {
        date: '2023-05-28',
        name: '*辰',
        money: 10,
        method: '支付宝',
        message: ''
    }, {
        date: '2023-06-01',
        name: '*名',
        money: 10,
        method: '微信',
        message: ''
    }, {
        date: '2023-06-01',
        name: '**森',
        money: 50,
        method: '支付宝',
        message: '大佬，我给你捐赠一杯咖啡，加油！'
    }, {
        date: '2023-06-12',
        name: '*帅',
        money: 6.66,
        method: '支付宝',
        message: '大佬，加油，找了好久的软件！'
    }, {
        date: '2023-06-13',
        name: '**鹏',
        money: 20,
        method: '支付宝',
        message: '支持一下:)'
    }
]